using AutoMapper;
using Runnatics.API.Models.Requests;
using Runnatics.Models.Client.Requests;
using Runnatics.Models.Client.Requests.CheckPoints;
using Runnatics.Models.Client.Requests.Devices;
using Runnatics.Models.Client.Requests.Events;
using Runnatics.Models.Client.Requests.Participant;
using Runnatics.Models.Client.Requests.Races;
using Runnatics.Models.Client.Responses;
using Runnatics.Models.Client.Responses.Checkpoints;
using Runnatics.Models.Client.Responses.Events;
using Runnatics.Models.Client.Responses.Participants;
using Runnatics.Models.Client.Responses.Races;
using Runnatics.Models.Client.Responses.Results;
using Runnatics.Models.Client.Responses.BibMapping;
using Runnatics.Models.Client.Responses.RFID;
using Runnatics.Models.Data.Common;
using Runnatics.Models.Data.Entities;
using Runnatics.Models.Data.EventOrganizers;
using Participant = Runnatics.Models.Data.Entities.Participant;

namespace Runnatics.Services.Mappings
{
    /// <summary>
    /// AutoMapper profile for mapping between data entities and client models
    /// </summary>
    public class AutoMapperMappingProfile : Profile
    {
        public AutoMapperMappingProfile()
        {
            // Organization mappings
            CreateMap<Organization, OrganizationResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.AuditProperties.IsActive))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate));

            // User mappings
            CreateMap<User, UserResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.TenantId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.TenantId))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.AuditProperties.IsActive))
                .ForMember(dest => dest.LastLoginAt, opt => opt.MapFrom(src => src.LastLoginAt))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate))
                .ForMember(dest => dest.ProfileImageUrl, opt => opt.Ignore()) // User entity doesn't have this field
                .ForMember(dest => dest.OrganizationName, opt => opt.MapFrom(src => src.Organization != null ? src.Organization.Name : string.Empty));

            // UserInvitation mappings
            CreateMap<UserInvitation, InvitationResponse>()
                .ForMember(dest => dest.InvitationId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role.ToString()))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src =>
                    src.IsAccepted ? "Accepted" :
                    src.IsExpired ? "Expired" :
                    DateTime.UtcNow > src.ExpiryDate ? "Expired" : "Pending"))
                .ForMember(dest => dest.ExpiresAt, opt => opt.MapFrom(src => src.ExpiryDate))
                .ForMember(dest => dest.InvitationLink, opt => opt.Ignore()); // This should be generated by the service

            // Request mappings
            CreateMap<InviteUserRequest, UserInvitation>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Generated
                .ForMember(dest => dest.TenantId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => Enum.Parse<UserRole>(src.Role)))
                .ForMember(dest => dest.Token, opt => opt.Ignore()) // Generated by service
                .ForMember(dest => dest.InvitedBy, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.ExpiryDate, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.IsAccepted, opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.IsExpired, opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.AcceptedAt, opt => opt.Ignore())
                .ForMember(dest => dest.AcceptedBy, opt => opt.Ignore())
                .ForMember(dest => dest.Organization, opt => opt.Ignore())
                .ForMember(dest => dest.InvitedByUser, opt => opt.Ignore())
                .ForMember(dest => dest.AcceptedByUser, opt => opt.Ignore());


            #region Event mappings
            CreateMap<EventRequest, Event>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.TenantId, opt => opt.Ignore()) // Set by service from JWT token
                .ForMember(dest => dest.Slug, opt => opt.Ignore()) // Not updatable via API
                .ForMember(dest => dest.Status, opt => opt.Ignore()) // Set server-side: Draft on create
                .ForMember(dest => dest.TimeZone, opt => opt.Ignore()) // Set server-side on create
                .ForMember(dest => dest.MaxParticipants, opt => opt.Ignore()) // Not set at creation time
                .ForMember(dest => dest.RegistrationDeadline, opt => opt.Ignore()) // Not set at creation time
                .ForMember(dest => dest.BannerImage, opt => opt.Ignore()) // Handled manually in service
                .ForMember(dest => dest.BannerContentType, opt => opt.Ignore())
                .ForMember(dest => dest.EventSettings, opt => opt.Ignore()) // Handled separately
                .ForMember(dest => dest.LeaderboardSettings, opt => opt.Ignore()) // Handled separately
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Organization, opt => opt.Ignore())
                .ForMember(dest => dest.EventOrganizer, opt => opt.Ignore())
                .ForMember(dest => dest.Races, opt => opt.Ignore())
                .ForMember(dest => dest.Checkpoints, opt => opt.Ignore())
                .ForMember(dest => dest.Participants, opt => opt.Ignore())
                .ForMember(dest => dest.ChipAssignments, opt => opt.Ignore())
                .ForMember(dest => dest.ReadRaws, opt => opt.Ignore())
                .ForMember(dest => dest.ReadNormalized, opt => opt.Ignore())
                .ForMember(dest => dest.SplitTimes, opt => opt.Ignore())
                .ForMember(dest => dest.Results, opt => opt.Ignore())
                .ForMember(dest => dest.EventOrganizerId, opt => opt.ConvertUsing<IdDecryptor, string>(src => src.EventOrganizerId));

            CreateMap<Event, EventResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.TenantId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.TenantId))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Slug, opt => opt.MapFrom(src => src.Slug))
                .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
                .ForMember(dest => dest.EventDate, opt => opt.MapFrom(src => src.EventDate))
                .ForMember(dest => dest.TimeZone, opt => opt.MapFrom(src => src.TimeZone))
                .ForMember(dest => dest.VenueName, opt => opt.MapFrom(src => src.VenueName))
                .ForMember(dest => dest.VenueAddress, opt => opt.MapFrom(src => src.VenueAddress))
                .ForMember(dest => dest.VenueLatitude, opt => opt.MapFrom(src => src.VenueLatitude))
                .ForMember(dest => dest.VenueLongitude, opt => opt.MapFrom(src => src.VenueLongitude))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.MaxParticipants, opt => opt.MapFrom(src => src.MaxParticipants))
                .ForMember(dest => dest.RegistrationDeadline, opt => opt.MapFrom(src => src.RegistrationDeadline))
                .ForMember(dest => dest.EventSettings, opt => opt.MapFrom(src => src.EventSettings))
                .ForMember(dest => dest.LeaderboardSettings, opt => opt.MapFrom(src => src.LeaderboardSettings))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.AuditProperties.IsActive))
                .ForMember(dest => dest.EventOrganizerId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.EventOrganizerId))
                .ForMember(dest => dest.EventOrganizerName, opt => opt.MapFrom(src => src.EventOrganizer.Name))
                .ForMember(dest => dest.BannerBase64, opt => opt.MapFrom(src => src.BannerImage));

            // EventSettings mappings
            CreateMap<EventSettingsRequest, EventSettings>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.EventId, opt => opt.Ignore())
                .ForMember(dest => dest.Event, opt => opt.Ignore())
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore())
                .ForMember(dest => dest.RemoveBanner, opt => opt.Ignore())
                .ForMember(dest => dest.ShowResultSummaryForRaces, opt => opt.Ignore())
                .ForMember(dest => dest.UseOldData, opt => opt.Ignore())
                .ForMember(dest => dest.AllowParticipantEdit, opt => opt.Ignore());

            CreateMap<EventSettings, EventSettingsResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.EventId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.EventId))
                .ForMember(dest => dest.RemoveBanner, opt => opt.MapFrom(src => src.RemoveBanner))
                .ForMember(dest => dest.Published, opt => opt.MapFrom(src => src.Published))
                .ForMember(dest => dest.RankOnNet, opt => opt.MapFrom(src => src.RankOnNet))
                .ForMember(dest => dest.ShowResultSummaryForRaces, opt => opt.MapFrom(src => src.ShowResultSummaryForRaces))
                .ForMember(dest => dest.UseOldData, opt => opt.MapFrom(src => src.UseOldData))
                .ForMember(dest => dest.ConfirmedEvent, opt => opt.MapFrom(src => src.ConfirmedEvent))
                .ForMember(dest => dest.AllowNameCheck, opt => opt.MapFrom(src => src.AllowNameCheck))
                .ForMember(dest => dest.AllowParticipantEdit, opt => opt.MapFrom(src => src.AllowParticipantEdit))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate));

            // LeaderboardSettings mappings
            CreateMap<LeaderboardSettingsRequest, LeaderboardSettings>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.EventId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Event, opt => opt.Ignore())
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore())
                .ForMember(dst => dst.AutoRefreshIntervalSec, opt => opt.MapFrom(src => src.AutoRefreshIntervalSec ?? 0))
                .ForMember(dst => dst.MaxDisplayedRecords, opt => opt.MapFrom(src => src.MaxDisplayedRecords ?? 0))
                .ForMember(dst => dst.NumberOfResultsToShowCategory, opt => opt.MapFrom(src => src.NumberOfResultsToShowCategory ?? 0))
                .ForMember(dst => dst.NumberOfResultsToShowOverall, opt => opt.MapFrom(src => src.NumberOfResultsToShowOverall ?? 0))
                .ForMember(dst => dst.EnableLiveLeaderboard, opt => opt.MapFrom(src => false));

            CreateMap<LeaderboardSettings, LeaderboardSettingsResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.EventId, opt => opt.ConvertUsing<NullableIdEncryptor, int?>(src => src.EventId))
                .ForMember(dest => dest.ShowOverallResults, opt => opt.MapFrom(src => src.ShowOverallResults))
                .ForMember(dest => dest.ShowCategoryResults, opt => opt.MapFrom(src => src.ShowCategoryResults))
                .ForMember(dest => dest.ShowGenderResults, opt => opt.MapFrom(src => src.ShowGenderResults))
                .ForMember(dest => dest.ShowAgeGroupResults, opt => opt.MapFrom(src => src.ShowAgeGroupResults))
                .ForMember(dest => dest.SortByOverallChipTime, opt => opt.MapFrom(src => src.SortByOverallChipTime))
                .ForMember(dest => dest.SortByOverallGunTime, opt => opt.MapFrom(src => src.SortByOverallGunTime))
                .ForMember(dest => dest.SortByCategoryChipTime, opt => opt.MapFrom(src => src.SortByCategoryChipTime))
                .ForMember(dest => dest.SortByCategoryGunTime, opt => opt.MapFrom(src => src.SortByCategoryGunTime))
                .ForMember(dest => dest.NumberOfResultsToShowCategory, opt => opt.MapFrom(src => src.NumberOfResultsToShowCategory))
                .ForMember(dest => dest.NumberOfResultsToShowOverall, opt => opt.MapFrom(src => src.NumberOfResultsToShowOverall))
                .ForMember(dest => dest.EnableLiveLeaderboard, opt => opt.MapFrom(src => src.EnableLiveLeaderboard))
                .ForMember(dest => dest.ShowSplitTimes, opt => opt.MapFrom(src => src.ShowSplitTimes))
                .ForMember(dest => dest.ShowPace, opt => opt.MapFrom(src => src.ShowPace))
                .ForMember(dest => dest.ShowTeamResults, opt => opt.MapFrom(src => src.ShowTeamResults))
                .ForMember(dest => dest.ShowMedalIcon, opt => opt.MapFrom(src => src.ShowMedalIcon))
                .ForMember(dest => dest.AllowAnonymousView, opt => opt.MapFrom(src => src.AllowAnonymousView))
                .ForMember(dest => dest.AutoRefreshIntervalSec, opt => opt.MapFrom(src => src.AutoRefreshIntervalSec))
                .ForMember(dest => dest.MaxDisplayedRecords, opt => opt.MapFrom(src => src.MaxDisplayedRecords))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate));

            CreateMap<EventOrganizer, EventOrganizerResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.TenantId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.TenantId))
                .ForMember(dest => dest.OrganizerName, opt => opt.MapFrom(src => src.Name));

            CreateMap<EventOrganizerResponse, EventOrganizer>()
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.OrganizerName));

            CreateMap<EventOrganizerRequest, EventOrganizer>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.TenantId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.EventOrganizerName));
            #endregion

            #region Races mappings
            CreateMap<RaceRequest, Race>()
                .ForMember(d => d.Id, opt => opt.Ignore())
                .ForMember(d => d.AuditProperties, opt => opt.Ignore())
                .ForMember(d => d.RaceSettings, opt => opt.Ignore())
                .ForMember(d => d.Participants, opt => opt.Ignore())
                .ForMember(d => d.Results, opt => opt.Ignore());

            CreateMap<RaceSettingsRequest, RaceSettings>()
                .ForMember(d => d.Id, opt => opt.Ignore())
                .ForMember(d => d.RaceId, opt => opt.Ignore())
                .ForMember(d => d.AuditProperties, opt => opt.Ignore())
                .ForMember(d => d.Race, opt => opt.Ignore());

            CreateMap<Race, RaceResponse>()
                .ForMember(d => d.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(d => d.EventId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.EventId))
                .ForMember(d => d.Title, opt => opt.MapFrom(src => src.Title))
                .ForMember(d => d.Distance, opt => opt.MapFrom(src => src.Distance))
                .ForMember(d => d.StartTime, opt => opt.MapFrom(src => src.StartTime))
                .ForMember(d => d.EndTime, opt => opt.MapFrom(src => src.EndTime))
                .ForMember(d => d.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(d => d.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate))
                .ForMember(d => d.IsActive, opt => opt.MapFrom(src => src.AuditProperties.IsActive))
                .ForMember(d => d.Description, opt => opt.MapFrom(src => src.Description))
                .ForMember(d => d.MaxParticipants, opt => opt.MapFrom(src => src.MaxParticipants))
                .ForMember(d => d.RaceSettings, opt => opt.MapFrom(src => src.RaceSettings))
                .ForMember(d => d.Event, opt => opt.MapFrom(src => src.Event))
                .ForMember(d => d.TotalParticipants, opt => opt.Ignore()) // Computed in service
                .ForMember(d => d.EncodedEpcCount, opt => opt.Ignore()); // Computed in service

            CreateMap<RaceSettings, RaceSettingsResponse>()
                .ForMember(d => d.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(d => d.RaceId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.RaceId))
                .ForMember(d => d.Published, opt => opt.MapFrom(src => src.Published))
                .ForMember(d => d.SendSms, opt => opt.MapFrom(src => src.SendSms))
                .ForMember(d => d.CheckValidation, opt => opt.MapFrom(src => src.CheckValidation))
                .ForMember(d => d.ShowLeaderboard, opt => opt.MapFrom(src => src.ShowLeaderboard))
                .ForMember(d => d.ShowResultTable, opt => opt.MapFrom(src => src.ShowResultTable))
                .ForMember(d => d.IsTimed, opt => opt.MapFrom(src => src.IsTimed))
                .ForMember(d => d.PublishDnf, opt => opt.MapFrom(src => src.PublishDnf))
                .ForMember(d => d.DedUpSeconds, opt => opt.MapFrom(src => src.DedUpSeconds))
                .ForMember(d => d.EarlyStartCutOff, opt => opt.MapFrom(src => src.EarlyStartCutOff))
                .ForMember(d => d.LateStartCutOff, opt => opt.MapFrom(src => src.LateStartCutOff))
                .ForMember(d => d.HasLoops, opt => opt.MapFrom(src => src.HasLoops))
                .ForMember(d => d.LoopLength, opt => opt.MapFrom(src => src.LoopLength))
                .ForMember(d => d.DataHeaders, opt => opt.MapFrom(src => src.DataHeaders))
                .ForMember(d => d.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(d => d.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate));

            CreateMap<LeaderboardSettingsRequest, LeaderboardSettings>()
                .ForMember(d => d.EventId, opt => opt.Ignore())
                .ForMember(d => d.Id, opt => opt.Ignore())
                .ForMember(d => d.ShowMedalIcon, opt => opt.MapFrom(src => src.ShowMedalIcon))
                .ForMember(d => d.AuditProperties, opt => opt.Ignore())
                .ForMember(d => d.AllowAnonymousView, opt => opt.MapFrom(src => src.AllowAnonymousView))
                .ForMember(d => d.AutoRefreshIntervalSec, opt => opt.MapFrom(src => src.AutoRefreshIntervalSec ?? 0))
                .ForMember(d => d.MaxDisplayedRecords, opt => opt.MapFrom(src => src.MaxDisplayedRecords ?? 0))
                .ForMember(d => d.NumberOfResultsToShowCategory, opt => opt.MapFrom(src => src.NumberOfResultsToShowCategory ?? 0))
                .ForMember(d => d.NumberOfResultsToShowOverall, opt => opt.MapFrom(src => src.NumberOfResultsToShowOverall ?? 0))
                .ForMember(d => d.EnableLiveLeaderboard, opt => opt.MapFrom(src => false))
                .ForMember(d => d.Event, opt => opt.Ignore());

            #endregion

            #region Participant mappings

            CreateMap<Models.Data.Entities.Participant, Models.Client.Responses.Participants.Participant>()
                .ForMember(d => d.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(d => d.Bib, opt => opt.MapFrom(src => src.BibNumber ?? ""))
                .ForMember(d => d.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(d => d.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(d => d.Email, opt => opt.MapFrom(src => src.Email ?? ""))
                .ForMember(d => d.Phone, opt => opt.MapFrom(src => src.Phone ?? ""))
                .ForMember(d => d.Gender, opt => opt.MapFrom(src => src.Gender ?? ""))
                .ForMember(d => d.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
                .ForMember(d => d.Age, opt => opt.MapFrom(src => src.Age))
                .ForMember(d => d.City, opt => opt.MapFrom(src => src.City ?? ""))
                .ForMember(d => d.State, opt => opt.MapFrom(src => src.State ?? ""))
                .ForMember(d => d.RegistrationStatus, opt => opt.MapFrom(src => src.Status))
                .ForMember(d => d.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(d => d.RaceName, opt => opt.MapFrom(src => src.Race != null ? src.Race.Title : ""))
                .ForMember(d => d.ImportBatchId, opt => opt.MapFrom(src => src.ImportBatchId));


            CreateMap<ImportBatch, ParticipantImportResponse>()
                .ForMember(d => d.ImportBatchId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(d => d.FileName, opt => opt.MapFrom(src => src.FileName))
                .ForMember(d => d.TotalRecords, opt => opt.MapFrom(src => src.TotalRecords))
                // .ForMember(d => d.ValidRecords, opt => opt.MapFrom(src => src.SuccessCount))
                // .ForMember(d => d.InvalidRecords, opt => opt.MapFrom(src => src.ErrorCount))
                .ForMember(d => d.Status, opt => opt.MapFrom(src => src.Status))
                // .ForMember(d => d.UploadedAt, opt => opt.MapFrom(src => src.UploadedAt))
                .ForMember(d => d.Errors, opt => opt.Ignore());

            CreateMap<Participant, ParticipantSearchReponse>()
                .ForMember(dst => dst.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dst => dst.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dst => dst.LastName, src => src.MapFrom(s => s.LastName))
                .ForMember(dst => dst.Bib, opt => opt.MapFrom(src => src.BibNumber))
                .ForMember(dst => dst.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dst => dst.Phone, opt => opt.MapFrom(src => src.Phone))
                .ForMember(dst => dst.Gender, opt => opt.MapFrom(src => string.IsNullOrWhiteSpace(src.Gender) ? "Unknown" : src.Gender))
                .ForMember(dst => dst.Category, opt => opt.MapFrom(src => string.IsNullOrWhiteSpace(src.AgeCategory) ? "Unknown" : src.AgeCategory))
                .ForMember(dst => dst.FullName, opt => opt.MapFrom(src => $"{src.FirstName} {src.LastName}".Trim()))
                .ForMember(dst => dst.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dst => dst.CheckedIn, opt => opt.MapFrom(src => src.Status == "CheckedIn" || src.Status == "Started" || src.Status == "Finished"))
                .ForMember(dst => dst.ChipId, opt => opt.Ignore()) // Populated separately after mapping
                .ForMember(dst => dst.CheckpointTimes, opt => opt.Ignore()); // Populated separately after mapping

            CreateMap<ParticipantRequest, Participant>()
                .ForMember(dst => dst.Id, opt => opt.Ignore())
                .ForMember(dst => dst.TenantId, opt => opt.Ignore()) // Set by service
                .ForMember(dst => dst.EventId, opt => opt.Ignore()) // Set by service
                .ForMember(dst => dst.RaceId, opt => opt.Ignore()) // Set by service
                .ForMember(dst => dst.BibNumber, opt => opt.MapFrom(src => src.BibNumber))
                .ForMember(dst => dst.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dst => dst.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dst => dst.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dst => dst.Phone, opt => opt.MapFrom(src => src.Phone))
                .ForMember(dst => dst.Gender, opt => opt.MapFrom(src => src.Gender))
                .ForMember(dst => dst.AgeCategory, opt => opt.MapFrom(src => src.Category));

            CreateMap<Participant, Category>()
                .ForMember(dst => dst.CategoryName, opt => opt.MapFrom(src => src.AgeCategory));
            #endregion

            #region Device mappings
            CreateMap<Device, DevicesResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.DeviceMacAddress, opt => opt.MapFrom(src => src.DeviceMacAddress))
                .ForMember(dest => dest.Hostname, opt => opt.MapFrom(src => src.Hostname))
                .ForMember(dest => dest.IpAddress, opt => opt.MapFrom(src => src.IpAddress))
                .ForMember(dest => dest.FirmwareVersion, opt => opt.MapFrom(src => src.FirmwareVersion))
                .ForMember(dest => dest.ReaderModel, opt => opt.MapFrom(src => src.ReaderModel))
                .ForMember(dest => dest.IsOnline, opt => opt.MapFrom(src => src.IsOnline))
                .ForMember(dest => dest.LastSeenAt, opt => opt.MapFrom(src => src.LastSeenAt));

            CreateMap<DeviceRequest, Device>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.TenantId, opt => opt.Ignore())
                .ForMember(dest => dest.IsOnline, opt => opt.Ignore())
                .ForMember(dest => dest.LastSeenAt, opt => opt.Ignore())
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore());

            #endregion

            #region Checkpoint

            // Checkpoint mapping
            CreateMap<CheckpointRequest, Checkpoint>()
               .ForMember(dest => dest.Id, opt => opt.Ignore())
               .ForMember(dest => dest.EventId, opt => opt.Ignore())
               .ForMember(dest => dest.RaceId, opt => opt.Ignore())
               .ForMember(dest => dest.DeviceId, opt => opt.Ignore())
               .ForMember(dest => dest.ParentDeviceId, opt => opt.Ignore())
               .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
               .ForMember(dest => dest.DistanceFromStart, opt => opt.MapFrom(src => src.DistanceFromStart))
               .ForMember(dest => dest.IsMandatory, opt => opt.MapFrom(src => src.IsMandatory))
               .ForMember(dest => dest.AuditProperties, opt => opt.Ignore())
               .ForMember(dest => dest.Device, opt => opt.Ignore())
               .ForMember(dest => dest.ParentDevice, opt => opt.Ignore());


            // FIX: Single consolidated mapping for Checkpoint -> CheckpointResponse
            // Previously there were two CreateMap<Checkpoint, CheckpointResponse>() configurations
            // which was causing the second one to override parts of the first one
            CreateMap<Checkpoint, CheckpointResponse>()
                .ForMember(dest => dest.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.EventId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.EventId))
                .ForMember(dest => dest.RaceId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.RaceId))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.DistanceFromStart, opt => opt.MapFrom(src => src.DistanceFromStart))
                .ForMember(dest => dest.DeviceId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.DeviceId))
                .ForMember(dest => dest.ParentDeviceId, opt => opt.ConvertUsing<NullableIdEncryptor, int?>(src => src.ParentDeviceId))
                .ForMember(dest => dest.IsMandatory, opt => opt.MapFrom(src => src.IsMandatory))
                // Device names from navigation properties (consolidated from duplicate mapping)
                .ForMember(dest => dest.DeviceName, opt => opt.MapFrom(src => src.Device != null ? src.Device.Name : string.Empty))
                .ForMember(dest => dest.ParentDeviceName, opt => opt.MapFrom(src => src.ParentDevice != null ? src.ParentDevice.Name : string.Empty));

            // RegisterDeviceRequest
            CreateMap<RegisterDeviceRequest, Device>()
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.DeviceName))
                .ForMember(dest => dest.Hostname, opt => opt.MapFrom(src => src.Hostname))
                .ForMember(dest => dest.TenantId, opt => opt.MapFrom(src => src.TenantId))
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.DeviceMacAddress, opt => opt.Ignore())
                .ForMember(dest => dest.IpAddress, opt => opt.Ignore())
                .ForMember(dest => dest.FirmwareVersion, opt => opt.Ignore())
                .ForMember(dest => dest.ReaderModel, opt => opt.Ignore())
                .ForMember(dest => dest.IsOnline, opt => opt.Ignore())
                .ForMember(dest => dest.LastSeenAt, opt => opt.Ignore())
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore());

            // R700ReaderInfo → Device (reader hardware details on create/update)
            CreateMap<R700ReaderInfo, Device>()
                .ForMember(dest => dest.IpAddress, opt => opt.MapFrom(src => src.IpAddress))
                .ForMember(dest => dest.FirmwareVersion, opt => opt.MapFrom(src => src.Firmware))
                .ForMember(dest => dest.ReaderModel, opt => opt.MapFrom(src => src.Model))
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.DeviceMacAddress, opt => opt.Ignore())
                .ForMember(dest => dest.Name, opt => opt.Ignore())
                .ForMember(dest => dest.TenantId, opt => opt.Ignore())
                .ForMember(dest => dest.Hostname, opt => opt.Ignore())
                .ForMember(dest => dest.IsOnline, opt => opt.Ignore())
                .ForMember(dest => dest.LastSeenAt, opt => opt.Ignore())
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore());

            CreateMap<CheckpointRequest, Checkpoint>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.EventId, opt => opt.Ignore())
                .ForMember(dest => dest.RaceId, opt => opt.Ignore())
                .ForMember(dest => dest.DeviceId, opt => opt.Ignore())
                .ForMember(dest => dest.ParentDeviceId, opt => opt.Ignore())
                .ForMember(dest => dest.IsMandatory, opt => opt.MapFrom(src => src.IsMandatory));

            // NOTE: Duplicate CreateMap<Checkpoint, CheckpointResponse> removed.
            // The consolidated mapping at line 349 already includes DeviceName and ParentDeviceName.
            // A second CreateMap for the same types causes AutoMapper to override the first (last-wins),
            // which was dropping all IdEncryptor mappings and causing 500 errors.

            #endregion Checkpoint

            #region RFID Results Mappings

            // Entity to Response mappings
            CreateMap<Results, CalculateResultsResponse>()
                .ForMember(dest => dest.TotalFinishers, opt => opt.Ignore())
                .ForMember(dest => dest.ResultsCreated, opt => opt.Ignore())
                .ForMember(dest => dest.ResultsUpdated, opt => opt.Ignore())
                .ForMember(dest => dest.DNFCount, opt => opt.Ignore())
                .ForMember(dest => dest.CategoriesProcessed, opt => opt.Ignore())
                .ForMember(dest => dest.GenderStats, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.Message, opt => opt.Ignore())
                .ForMember(dest => dest.ProcessedAt, opt => opt.Ignore())
                .ForMember(dest => dest.ProcessingTimeMs, opt => opt.Ignore());

            // ReadNormalized to Results mapping helper
            CreateMap<ReadNormalized, Results>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.FinishTime, src => src.MapFrom(s => s.GunTime))
                .ForMember(dest => dest.GunTime, src => src.MapFrom(s => s.GunTime))
                .ForMember(dest => dest.NetTime, src => src.MapFrom(s => s.NetTime))
                .ForMember(dest => dest.OverallRank, opt => opt.Ignore())
                .ForMember(dest => dest.GenderRank, opt => opt.Ignore())
                .ForMember(dest => dest.CategoryRank, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => "Finished"))
                .ForMember(dest => dest.DisqualificationReason, opt => opt.Ignore())
                .ForMember(dest => dest.IsOfficial, opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.CertificateGenerated, opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.RaceId, opt => opt.Ignore())
                .ForMember(dest => dest.Event, opt => opt.Ignore())
                .ForMember(dest => dest.Participant, opt => opt.Ignore())
                .ForMember(dest => dest.Race, opt => opt.Ignore());

            #endregion RFID Results Mappings

            #region Race Results API Mappings

            // Checkpoint to CheckpointInfoResponse
            CreateMap<Checkpoint, CheckpointInfoResponse>()
                .ForMember(dest => dest.CheckpointId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name ?? $"Checkpoint {src.Id}"))
                .ForMember(dest => dest.DistanceFromStart, opt => opt.MapFrom(src => src.DistanceFromStart))
                .ForMember(dest => dest.IsMandatory, opt => opt.MapFrom(src => src.IsMandatory))
                .ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.Device != null ? src.Device.DeviceMacAddress : string.Empty))
                .ForMember(dest => dest.DeviceName, opt => opt.MapFrom(src => src.Device != null ? src.Device.Name : string.Empty));

            // Participant to RaceParticipantResultResponse (basic mapping, times calculated in service)
            CreateMap<Participant, RaceParticipantResultResponse>()
                .ForMember(dest => dest.ParticipantId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(dest => dest.Bib, opt => opt.MapFrom(src => src.BibNumber ?? string.Empty))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName ?? string.Empty))
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName ?? string.Empty))
                .ForMember(dest => dest.FullName, opt => opt.MapFrom(src => src.FullName))
                .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender ?? string.Empty))
                .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.AgeCategory ?? string.Empty))
                .ForMember(dest => dest.ChipId, opt => opt.Ignore()) // Set in service from ChipAssignment
                .ForMember(dest => dest.Status, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.Rank, opt => opt.MapFrom(src => src.Result != null ? src.Result.OverallRank : null))
                .ForMember(dest => dest.TotalTime, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.TotalTimeSeconds, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.AveragePace, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.AverageSpeed, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.CheckpointTimes, opt => opt.Ignore()); // Built in service

            // ReadNormalized to CheckpointTimeResponse (for checkpoint crossing times)
            CreateMap<ReadNormalized, CheckpointTimeResponse>()
                .ForMember(dest => dest.CheckpointId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.CheckpointId))
                .ForMember(dest => dest.CheckpointName, opt => opt.MapFrom(src => src.Checkpoint != null ? src.Checkpoint.Name : string.Empty))
                .ForMember(dest => dest.CrossingTime, opt => opt.MapFrom(src => src.ChipTime))
                .ForMember(dest => dest.DistanceFromStart, opt => opt.MapFrom(src => src.Checkpoint != null ? src.Checkpoint.DistanceFromStart : 0))
                .ForMember(dest => dest.Passed, opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.TimeFromStart, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.TimeFromStartSeconds, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.SplitTime, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.SplitTimeSeconds, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.Rank, opt => opt.Ignore()); // Calculated in service

            #endregion Race Results API Mappings

            #region Leaderboard Mappings

            CreateMap<Results, LeaderboardEntry>()
                .ForMember(dest => dest.Rank, opt => opt.Ignore()) // Set in service based on RankBy
                .ForMember(dest => dest.ParticipantId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.ParticipantId))
                .ForMember(dest => dest.Bib, opt => opt.MapFrom(src => src.Participant.BibNumber ?? string.Empty))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.Participant.FirstName ?? string.Empty))
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.Participant.LastName ?? string.Empty))
                .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Participant.Gender ?? string.Empty))
                .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Participant.AgeCategory))
                .ForMember(dest => dest.Age, opt => opt.MapFrom(src => src.Participant.Age))
                .ForMember(dest => dest.City, opt => opt.MapFrom(src => src.Participant.City ?? string.Empty))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Participant.Email))
                .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Participant.Phone))
                .ForMember(dest => dest.FinishTimeMs, opt => opt.MapFrom(src => src.FinishTime))
                .ForMember(dest => dest.GunTimeMs, opt => opt.MapFrom(src => src.GunTime))
                .ForMember(dest => dest.NetTimeMs, opt => opt.MapFrom(src => src.NetTime))
                .ForMember(dest => dest.FinishTime, opt => opt.Ignore()) // Formatted in service
                .ForMember(dest => dest.GunTime, opt => opt.Ignore()) // Formatted in service
                .ForMember(dest => dest.NetTime, opt => opt.Ignore()) // Formatted in service
                .ForMember(dest => dest.OverallRank, opt => opt.MapFrom(src => src.OverallRank))
                .ForMember(dest => dest.GenderRank, opt => opt.MapFrom(src => src.GenderRank))
                .ForMember(dest => dest.CategoryRank, opt => opt.MapFrom(src => src.CategoryRank))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.AveragePace, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.AveragePaceFormatted, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.Splits, opt => opt.Ignore()); // Loaded separately in service

            CreateMap<SplitTimes, Runnatics.Models.Client.Responses.Results.SplitTimeInfo>()
                .ForMember(dest => dest.CheckpointId, opt => opt.ConvertUsing<NullableIdEncryptor, int?>(src => src.CheckpointId))
                .ForMember(dest => dest.CheckpointName, opt => opt.MapFrom(src => src.Checkpoint.Name ?? $"CP{src.Checkpoint.DistanceFromStart}km"))
                .ForMember(dest => dest.DistanceKm, opt => opt.MapFrom(src => src.Checkpoint.DistanceFromStart))
                .ForMember(dest => dest.SplitTimeMs, opt => opt.MapFrom(src => src.SplitTimeMs ?? 0))
                .ForMember(dest => dest.SegmentTimeMs, opt => opt.MapFrom(src => src.SegmentTime))
                .ForMember(dest => dest.CumulativeTimeMs, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.SplitTime, opt => opt.Ignore()) // Formatted in service
                .ForMember(dest => dest.SegmentTime, opt => opt.Ignore()) // Formatted in service
                .ForMember(dest => dest.CumulativeTime, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.Pace, opt => opt.MapFrom(src => src.Pace))
                .ForMember(dest => dest.PaceFormatted, opt => opt.Ignore()) // Formatted in service
                .ForMember(dest => dest.Rank, opt => opt.MapFrom(src => src.Rank))
                .ForMember(dest => dest.GenderRank, opt => opt.MapFrom(src => src.GenderRank))
                .ForMember(dest => dest.CategoryRank, opt => opt.MapFrom(src => src.CategoryRank));

            #endregion Leaderboard Mappings

            #region Participant Details Mappings

            CreateMap<Participant, ParticipantDetailsResponse>()
                .ForMember(d => d.Id, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.Id))
                .ForMember(d => d.EventId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.EventId))
                .ForMember(d => d.EventName, opt => opt.MapFrom(src => src.Event != null ? src.Event.Name : null))
                .ForMember(d => d.RaceId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.RaceId))
                .ForMember(d => d.RaceName, opt => opt.MapFrom(src => src.Race != null ? src.Race.Title : null))
                .ForMember(d => d.RaceDistance, opt => opt.MapFrom(src => src.Race != null ? src.Race.Distance : null))
                .ForMember(d => d.StartTime, opt => opt.MapFrom(src => src.Race != null ? src.Race.StartTime : null))
                .ForMember(d => d.Club, opt => opt.Ignore())
                .ForMember(d => d.ChipTime, opt => opt.Ignore())
                .ForMember(d => d.GunTime, opt => opt.Ignore())
                .ForMember(d => d.FinishTime, opt => opt.Ignore())
                .ForMember(d => d.Performance, opt => opt.Ignore())
                .ForMember(d => d.Rankings, opt => opt.Ignore())
                .ForMember(d => d.CheckpointTimes, opt => opt.Ignore())
                .ForMember(d => d.SplitTimes, opt => opt.Ignore())
                .ForMember(d => d.PaceProgression, opt => opt.Ignore())
                .ForMember(d => d.Epc, opt => opt.Ignore())
                .ForMember(d => d.RfidReadings, opt => opt.Ignore())
                .ForMember(d => d.RawRfidTagReadings, opt => opt.Ignore())
                .ForMember(d => d.ProcessingNotes, opt => opt.Ignore())
                .ForMember(d => d.IsManualResult, opt => opt.MapFrom(src => src.IsManualTiming));

            CreateMap<SplitTimes, Runnatics.Models.Client.Responses.Participants.SplitTimeInfo>()
                .ForMember(d => d.CheckpointId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.ToCheckpointId))
                .ForMember(d => d.CheckpointName, opt => opt.MapFrom(src => src.ToCheckpoint != null ? src.ToCheckpoint.Name : null))
                .ForMember(d => d.DistanceKm, opt => opt.MapFrom(src => src.ToCheckpoint != null ? (decimal?)src.ToCheckpoint.DistanceFromStart : src.Distance))
                .ForMember(d => d.Distance, opt => opt.MapFrom(src => src.ToCheckpoint != null ? $"{src.ToCheckpoint.DistanceFromStart} km" : null))
                .ForMember(d => d.OverallRank, opt => opt.MapFrom(src => src.Rank))
                .ForMember(d => d.GenderRank, opt => opt.MapFrom(src => src.GenderRank))
                .ForMember(d => d.CategoryRank, opt => opt.MapFrom(src => src.CategoryRank))
                .ForMember(d => d.SplitTime, opt => opt.Ignore())
                .ForMember(d => d.CumulativeTime, opt => opt.Ignore())
                .ForMember(d => d.Pace, opt => opt.Ignore())
                .ForMember(d => d.PaceValue, opt => opt.Ignore())
                .ForMember(d => d.Speed, opt => opt.Ignore())
                .ForMember(d => d.IsManual, opt => opt.MapFrom(src => src.ReadNormalized != null && src.ReadNormalized.IsManualEntry));

            CreateMap<SplitTimes, PaceProgressionInfo>()
                .ForMember(d => d.DistanceKm, opt => opt.MapFrom(src => src.ToCheckpoint != null ? (decimal?)src.ToCheckpoint.DistanceFromStart : src.Distance))
                .ForMember(d => d.Segment, opt => opt.Ignore())
                .ForMember(d => d.Pace, opt => opt.Ignore())
                .ForMember(d => d.PaceValue, opt => opt.Ignore())
                .ForMember(d => d.Speed, opt => opt.Ignore())
                .ForMember(d => d.SplitTime, opt => opt.Ignore())
                .ForMember(d => d.PaceChangeDirection, opt => opt.Ignore())
                .ForMember(d => d.PaceChangePercent, opt => opt.Ignore());

            CreateMap<ReadNormalized, RfidReadingDetail>()
                .ForMember(d => d.ReadingId, opt => opt.MapFrom(src => src.Id))
                .ForMember(d => d.ReadTimeUtc, opt => opt.MapFrom(src => src.ChipTime))
                .ForMember(d => d.ReadTimeLocal, opt => opt.Ignore()) // Converted in service using event timezone
                .ForMember(d => d.CheckpointName, opt => opt.MapFrom(src =>
                    src.Checkpoint != null ? src.Checkpoint.Name : null))
                .ForMember(d => d.DeviceName, opt => opt.MapFrom(src =>
                    src.Checkpoint != null && src.Checkpoint.Device != null
                        ? src.Checkpoint.Device.Name
                        : null))
                .ForMember(d => d.GunTimeMs, opt => opt.MapFrom(src => src.GunTime))
                .ForMember(d => d.GunTimeFormatted, opt => opt.Ignore()) // Formatted in service
                .ForMember(d => d.NetTimeMs, opt => opt.MapFrom(src => src.NetTime))
                .ForMember(d => d.NetTimeFormatted, opt => opt.Ignore()) // Formatted in service
                .ForMember(d => d.ChipId, opt => opt.Ignore()) // Set in service from ChipAssignment
                .ForMember(d => d.IsManualEntry, opt => opt.MapFrom(src => src.IsManualEntry))
                .ForMember(d => d.Notes, opt => opt.MapFrom(src => src.ManualEntryReason));

            #endregion Participant Details Mappings

            #region BibMapping mappings

            CreateMap<ChipAssignment, BibMappingResponse>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.ChipId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.ChipId))
                .ForMember(dest => dest.ParticipantId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.ParticipantId))
                .ForMember(dest => dest.EventId, opt => opt.ConvertUsing<IdEncryptor, int>(src => src.EventId))
                .ForMember(dest => dest.Epc, opt => opt.MapFrom(src => src.Chip.EPC))
                .ForMember(dest => dest.BibNumber, opt => opt.MapFrom(src => src.Participant.BibNumber ?? string.Empty))
                .ForMember(dest => dest.ParticipantName, opt => opt.MapFrom(src => src.Participant.FullName))
                .ForMember(dest => dest.RaceId, opt => opt.MapFrom((src, dest, destMember, ctx) =>
                    ctx.Items.TryGetValue("RaceId", out var raceId) ? (string)raceId! : string.Empty))
                .ForMember(dest => dest.AssignedAt, opt => opt.MapFrom((src, dest, destMember, ctx) =>
                {
                    var tz = ctx.Items.TryGetValue("DisplayTz", out var tzObj) ? (TimeZoneInfo)tzObj! : TimeZoneInfo.Utc;
                    return TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(src.AssignedAt, DateTimeKind.Utc), tz);
                }))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom((src, dest, destMember, ctx) =>
                {
                    var tz = ctx.Items.TryGetValue("DisplayTz", out var tzObj) ? (TimeZoneInfo)tzObj! : TimeZoneInfo.Utc;
                    return TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(src.AuditProperties.CreatedDate, DateTimeKind.Utc), tz);
                }));

            #endregion BibMapping mappings
        }
    }
}
