using AutoMapper;
using Runnatics.Models.Data.Entities;
using Runnatics.Models.Data.Common;
using Runnatics.Models.Client.Responses;
using Runnatics.Models.Client.Requests;
using Runnatics.Models.Client.Responses.Events;
using Runnatics.Models.Client.Requests.Events;
using Runnatics.Models.Data.EventOrganizers;
using Runnatics.API.Models.Requests;

namespace Runnatics.Services.Mappings
{
    /// <summary>
    /// AutoMapper profile for mapping between data entities and client models
    /// </summary>
    public class AutoMapperMappingProfile : Profile
    {
        public AutoMapperMappingProfile()
        {
            // Organization mappings
            CreateMap<Organization, OrganizationResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.AuditProperties.IsActive))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate));

            // User mappings
            CreateMap<User, UserResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.TenantId, opt => opt.MapFrom(src => src.TenantId))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.AuditProperties.IsActive))
                .ForMember(dest => dest.LastLoginAt, opt => opt.MapFrom(src => src.LastLoginAt))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate))
                .ForMember(dest => dest.ProfileImageUrl, opt => opt.Ignore()) // User entity doesn't have this field
                .ForMember(dest => dest.OrganizationName, opt => opt.MapFrom(src => src.Organization != null ? src.Organization.Name : string.Empty));

            // UserInvitation mappings
            CreateMap<UserInvitation, InvitationResponse>()
                .ForMember(dest => dest.InvitationId, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role.ToString()))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src =>
                    src.IsAccepted ? "Accepted" :
                    src.IsExpired ? "Expired" :
                    DateTime.UtcNow > src.ExpiryDate ? "Expired" : "Pending"))
                .ForMember(dest => dest.ExpiresAt, opt => opt.MapFrom(src => src.ExpiryDate))
                .ForMember(dest => dest.InvitationLink, opt => opt.Ignore()); // This should be generated by the service

            // Request mappings
            CreateMap<InviteUserRequest, UserInvitation>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Generated
                .ForMember(dest => dest.TenantId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => Enum.Parse<UserRole>(src.Role)))
                .ForMember(dest => dest.Token, opt => opt.Ignore()) // Generated by service
                .ForMember(dest => dest.InvitedBy, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.ExpiryDate, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.IsAccepted, opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.IsExpired, opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.AcceptedAt, opt => opt.Ignore())
                .ForMember(dest => dest.AcceptedBy, opt => opt.Ignore())
                .ForMember(dest => dest.Organization, opt => opt.Ignore())
                .ForMember(dest => dest.InvitedByUser, opt => opt.Ignore())
                .ForMember(dest => dest.AcceptedByUser, opt => opt.Ignore());


            //Event mappings
            CreateMap<EventRequest, Event>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.TenantId, opt => opt.Ignore()) // Set by service from JWT token
                .ForMember(dest => dest.EventSettings, opt => opt.Ignore()) // Handled separately
                .ForMember(dest => dest.LeaderboardSettings, opt => opt.Ignore()) // Handled separately
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Organization, opt => opt.Ignore())
                .ForMember(dest => dest.EventOrganizer, opt => opt.Ignore())
                .ForMember(dest => dest.Races, opt => opt.Ignore())
                .ForMember(dest => dest.Checkpoints, opt => opt.Ignore())
                .ForMember(dest => dest.Participants, opt => opt.Ignore())
                .ForMember(dest => dest.ChipAssignments, opt => opt.Ignore())
                .ForMember(dest => dest.ReadRaws, opt => opt.Ignore())
                .ForMember(dest => dest.ReadNormalized, opt => opt.Ignore())
                .ForMember(dest => dest.SplitTimes, opt => opt.Ignore())
                .ForMember(dest => dest.Results, opt => opt.Ignore())
                .ForMember(dest => dest.EventOrganizerId, opt => opt.MapFrom(src => src.EventOrganizerId));

            CreateMap<Event, EventResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.TenantId, opt => opt.MapFrom(src => src.TenantId))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Slug, opt => opt.MapFrom(src => src.Slug))
                .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
                .ForMember(dest => dest.EventDate, opt => opt.MapFrom(src => src.EventDate))
                .ForMember(dest => dest.TimeZone, opt => opt.MapFrom(src => src.TimeZone))
                .ForMember(dest => dest.VenueName, opt => opt.MapFrom(src => src.VenueName))
                .ForMember(dest => dest.VenueAddress, opt => opt.MapFrom(src => src.VenueAddress))
                .ForMember(dest => dest.VenueLatitude, opt => opt.MapFrom(src => src.VenueLatitude))
                .ForMember(dest => dest.VenueLongitude, opt => opt.MapFrom(src => src.VenueLongitude))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.MaxParticipants, opt => opt.MapFrom(src => src.MaxParticipants))
                .ForMember(dest => dest.RegistrationDeadline, opt => opt.MapFrom(src => src.RegistrationDeadline))
                .ForMember(dest => dest.EventSettings, opt => opt.MapFrom(src => src.EventSettings))
                .ForMember(dest => dest.LeaderboardSettings, opt => opt.MapFrom(src => src.LeaderboardSettings))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.AuditProperties.IsActive))
                .ForMember(dest => dest.City, opt => opt.Ignore()) // Legacy field
                .ForMember(dest => dest.EventOrganizerId, opt => opt.MapFrom(src => src.EventOrganizerId))
                .ForMember(dest => dest.EventOrganizerName, opt => opt.MapFrom(src => src.EventOrganizer.Name));

            // EventSettings mappings
            CreateMap<EventSettingsRequest, EventSettings>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.EventId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Event, opt => opt.Ignore())
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore()); // Set by service

            CreateMap<EventSettings, EventSettingsResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.EventId, opt => opt.MapFrom(src => src.EventId))
                .ForMember(dest => dest.RemoveBanner, opt => opt.MapFrom(src => src.RemoveBanner))
                .ForMember(dest => dest.Published, opt => opt.MapFrom(src => src.Published))
                .ForMember(dest => dest.RankOnNet, opt => opt.MapFrom(src => src.RankOnNet))
                .ForMember(dest => dest.ShowResultSummaryForRaces, opt => opt.MapFrom(src => src.ShowResultSummaryForRaces))
                .ForMember(dest => dest.UseOldData, opt => opt.MapFrom(src => src.UseOldData))
                .ForMember(dest => dest.ConfirmedEvent, opt => opt.MapFrom(src => src.ConfirmedEvent))
                .ForMember(dest => dest.AllowNameCheck, opt => opt.MapFrom(src => src.AllowNameCheck))
                .ForMember(dest => dest.AllowParticipantEdit, opt => opt.MapFrom(src => src.AllowParticipantEdit))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate));

            // LeaderboardSettings mappings
            CreateMap<LeaderboardSettingsRequest, LeaderboardSettings>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.EventId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Event, opt => opt.Ignore())
                .ForMember(dest => dest.AuditProperties, opt => opt.Ignore()); // Set by service

            CreateMap<LeaderboardSettings, LeaderboardSettingsResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.EventId, opt => opt.MapFrom(src => src.EventId))
                .ForMember(dest => dest.ShowOverallResults, opt => opt.MapFrom(src => src.ShowOverallResults))
                .ForMember(dest => dest.ShowCategoryResults, opt => opt.MapFrom(src => src.ShowCategoryResults))
                .ForMember(dest => dest.ShowGenderResults, opt => opt.MapFrom(src => src.ShowGenderResults))
                .ForMember(dest => dest.ShowAgeGroupResults, opt => opt.MapFrom(src => src.ShowAgeGroupResults))
                .ForMember(dest => dest.SortByOverallChipTime, opt => opt.MapFrom(src => src.SortByOverallChipTime))
                .ForMember(dest => dest.SortByOverallGunTime, opt => opt.MapFrom(src => src.SortByOverallGunTime))
                .ForMember(dest => dest.SortByCategoryChipTime, opt => opt.MapFrom(src => src.SortByCategoryChipTime))
                .ForMember(dest => dest.SortByCategoryGunTime, opt => opt.MapFrom(src => src.SortByCategoryGunTime))
                .ForMember(dest => dest.NumberOfResultsToShowCategory, opt => opt.MapFrom(src => src.NumberOfResultsToShowCategory))
                .ForMember(dest => dest.NumberOfResultsToShowOverall, opt => opt.MapFrom(src => src.NumberOfResultsToShowOverall))
                .ForMember(dest => dest.EnableLiveLeaderboard, opt => opt.MapFrom(src => src.EnableLiveLeaderboard))
                .ForMember(dest => dest.ShowSplitTimes, opt => opt.MapFrom(src => src.ShowSplitTimes))
                .ForMember(dest => dest.ShowPace, opt => opt.MapFrom(src => src.ShowPace))
                .ForMember(dest => dest.ShowTeamResults, opt => opt.MapFrom(src => src.ShowTeamResults))
                .ForMember(dest => dest.ShowMedalIcon, opt => opt.MapFrom(src => src.ShowMedalIcon))
                .ForMember(dest => dest.AllowAnonymousView, opt => opt.MapFrom(src => src.AllowAnonymousView))
                .ForMember(dest => dest.AutoRefreshIntervalSec, opt => opt.MapFrom(src => src.AutoRefreshIntervalSec))
                .ForMember(dest => dest.MaxDisplayedRecords, opt => opt.MapFrom(src => src.MaxDisplayedRecords))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.AuditProperties.CreatedDate))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.AuditProperties.UpdatedDate));

            CreateMap<EventOrganizer, EventOrganizerResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.TenantId, opt => opt.MapFrom(src => src.TenantId))
                .ForMember(dest => dest.OrganizerName, opt => opt.MapFrom(src => src.Name));

            CreateMap<EventOrganizerResponse, EventOrganizer>()
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.OrganizerName));

            CreateMap<EventOrganizerRequest, EventOrganizer>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.TenantId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.EventOrganizerName));

        }
    }
}
